<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>GameTools.App</RootNamespace>
    <AssemblyName>GameTools.App</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameTools.Core\GameTools.Core.csproj" />
    <ProjectReference Include="..\GameTools.Win32\GameTools.Win32.csproj" />
    <ProjectReference Include="..\GameTools.Infrastructure\GameTools.Infrastructure.csproj" />
  </ItemGroup>

</Project>
