<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GameTools.Infrastructure</RootNamespace>
    <AssemblyName>GameTools.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameTools.Core\GameTools.Core.csproj" />
    <ProjectReference Include="..\GameTools.Win32\GameTools.Win32.csproj" />
  </ItemGroup>

</Project>
